# Generated by Django 3.2.9 on 2021-11-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_account_nick_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ageType',
            field=models.CharField(choices=[('A', 'Adult'), ('T', 'Teenager'), ('Y', 'Young')], default='Y', max_length=7),
        ),
    ]
