# Generated by Django 3.2.9 on 2021-11-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_account_agetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='isCoach',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='isReferee',
            field=models.BooleanField(default=False),
        ),
    ]
