# Generated by Django 3.2.9 on 2021-11-08 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0004_auto_20211108_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('city', models.TextField()),
                ('Images', models.FileField(blank=True, null=True, upload_to='')),
                ('discription', models.TextField(blank=True, null=True)),
                ('AllAwards', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('holdingDate', models.DateField()),
                ('location', models.TextField()),
                ('conditions', models.TextField()),
                ('EntranceFee', models.IntegerField()),
                ('Awards', models.TextField(blank=True)),
                ('registrationDate', models.DateField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Account.account')),
                ('races', models.ManyToManyField(to='varzeshkaran.Race')),
            ],
            options={
                'abstract': False,
            },
            bases=('Account.account',),
        ),
    ]
