# Generated by Django 3.2.9 on 2021-11-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varzeshkaran', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='city',
            field=models.CharField(max_length=30),
        ),
    ]
