# Generated by Django 3.2.9 on 2021-11-15 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_auto_20211108_1024'),
        ('varzeshkaran', '0002_alter_club_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Account.account')),
            ],
            options={
                'abstract': False,
            },
            bases=('Account.account',),
        ),
        migrations.CreateModel(
            name='Refree',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Account.account')),
            ],
            options={
                'abstract': False,
            },
            bases=('Account.account',),
        ),
    ]
