# Generated by Django 3.2.9 on 2021-11-16 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_auto_20211108_1024'),
        ('varzeshkaran', '0004_admin_clubid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminOfClub',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Account.account')),
                ('clubId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='varzeshkaran.club')),
            ],
            options={
                'abstract': False,
            },
            bases=('Account.account',),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
