# Generated by Django 3.2.9 on 2021-11-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varzeshkaran', '0005_auto_20211116_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminofclub',
            name='CertificationFile',
            field=models.FileField(max_length=254, null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='coach',
            name='CertificationFile',
            field=models.FileField(max_length=254, null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='refree',
            name='CertificationFile',
            field=models.FileField(max_length=254, null=True, upload_to=None),
        ),
    ]
